### ISSUE TITLE
RuntimeException - Could not find .../Guzzle/Http/Resources/cacert.pem

### ISSUE THREAD

**Issue by rdmendo** [Bee-Lab/bowerphp#157] opened 2016-12-24 11:05 UTC
[RuntimeException]
bowerphp.phar/vendor/guzzle/guzzle/src/Guzzle/Http/Resources/cacert.pem

PS: Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

**Comment by garak** [comment] 2016-12-24 15:47
`guzzle/guzzle` is a dependency of `knplabs/github-api`.
I tried to upgrade `knplabs/github-api` to `2.*`, but it changed a lot since `1.*` and it's a mess.

**Comment by garak** [comment] 2017-04-22 10:03
I'm closing this since I cannot reproduce. I just tried to compile from source (using `bin/console compile 1`) and .pem file is there

**Closed by garak** 2017-04-22 10:03 UTC
